name: tuf-test-vectors CI docker images update
on:
  push:
    branches: [ master ]
jobs:
  update-bionic:
    name: Update Ubuntu Bionic Image
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: docker.pkg.github.com/advancedtelematic/tuf-test-vectors/tuf-test-vectors-ci:bionic-master
      DOCKERFILE: ci/gitlab/Dockerfile.tuf-test-vectors
    steps:
      - uses: actions/checkout@master
      - name: Docker login
        run: echo ${{ github.token }} | docker login docker.pkg.github.com -u advancedtelematic --password-stdin
      - name: Docker build and push
        run: |
          docker pull "$DOCKER_TAG" || true
          docker build --cache-from "$DOCKER_TAG" --pull -t "$DOCKER_TAG" -f "$DOCKERFILE" .
          docker push "$DOCKER_TAG" 
